config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home do
  	resources :posts
  end	

  resources :posts do
  	resources :comments
  end


  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "60x60#" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user = current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else render 'new'
		end 
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment)) 
			redirect_to post_path(@post)
		else
			render 'edit'
	end
			
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

	def index
    @posts = Post.all.order("created_at DESC")
	end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

	def new
		@post = Post.new
	end 

	def create
		@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
    end
	end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

	private

  def find_post
    @post = Post.find(params[:id])
  end

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.date 
			= comment.user.email
			at 
			= comment.created_at.strftime("%H:%M %d-%b-%y")
		%p.comment_content= comment.comment	
	.buttons	
		= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure you want to delete your comment?"}
		= link_to "Edit", edit_post_comment_path(comment.post, comment)

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment, label: false
	= f.submit

app/views/comments/edit.html.haml
%h1 Edit

= simple_form_for([@post, @comment]) do |f|
	= f.input :comment
	= f.submit 

app/views/layouts/application.html.haml
!!!
%html
%head
	%title TCD Hub
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext", type: "text/css"}
	%link{ rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css"}
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	= javascript_include_tag 'jquery'
	= javascript_include_tag 'jquery.sticky'
	-# <META HTTP-EQUIV="refresh" CONTENT="20">

	:javascript
		$(window).load(function(){
		$("header").sticky({ topSpacing: 0 });
		});

%body

	%header.main_header.clearfix
		.wrapper
			#logo
				%p= link_to 'tcd hub', root_path
			#buttons
				- if user_signed_in?
					= link_to current_user.email
				- else
					= link_to "Sign Up", new_user_registration_path
					= link_to "Sign In", new_user_session_path

	.wrapper
		%p.notice= notice
		%p.alert= alert

	.wrapper
		=yield

app/views/posts/_form.html.haml
#form
	= simple_form_for @post, html: { multipart: true } do |f|
		%h3 Title
		%h3= f.input :title, label: false
		%h3 Content
		%h3= f.input :content, label: false
		%h3= f.submit
		= f.label "Attach Image", :image
		= f.file_field :image	

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post	
			%p.date 
				= post.created_at.strftime("%H:%M %d-%b-%y")
				by
				= post.user.email

			%h2.title= link_to post.title, post

			%p.image
				- if post.image?
					= image_tag post.image(:thumb)

app/views/posts/new.html.haml
#new_post

	= render 'form'

app/views/posts/show.html.haml
#post_content
	.original_post
		.info
			= @post.user.email
			at 
			= @post.created_at.strftime("%H:%M %d-%b-%y")

		.buttons
			= link_to "Edit", edit_post_path(@post)
			= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?"}

		.image
			- if @post.image?
				= image_tag @post.image(:medium)	

		%p= @post.content


	#comments
		%h2
			= @post.comments.count
			Comments
		= render @post.comments


		%h3 Reply to thread
		= render "comments/form"